sylius_resource:
    resources:
        griffephotos.option_dependency_plugin.option_dependency:
            classes:
                model: GriffePhotos\OptionDependencyPlugin\Entity\OptionDependency
                interface: GriffePhotos\OptionDependencyPlugin\Entity\OptionDependencyInterface
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: GriffePhotos\OptionDependencyPlugin\Repository\OptionDependencyRepository
                factory: Sylius\Component\Resource\Factory\Factory
                form: GriffePhotos\OptionDependencyPlugin\Form\Type\OptionDependencyType
            templates: "@GriffePhotosOptionDependencyPlugin/Admin/OptionDependency"
