sylius_resource:
    resources:
        GriffePhotos.option_dependency_plugin.option_dependency:
            classes:
                model: GriffePhotos\OptionDependencyPlugin\Entity\OptionDependency
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                form:
                    default: GriffePhotos\OptionDependencyPlugin\Form\Type\OptionDependencyType
