# Delete these routes and define your own shop routes here

GriffePhotos_sylius_example_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: GriffePhotos\SyliusExamplePlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

GriffePhotos_sylius_example_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: GriffePhotos\SyliusExamplePlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
